repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
    -   id: check-docstring-first
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/add-trailing-comma
    rev: ''
    hooks:
    -   id: add-trailing-comma

-   repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=80]
        language_version: python3
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
        args: [--skip-string-normalization, --line-length=80]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy

  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        additional_dependencies:
          - toml
