"""add product_category table

Revision ID: 01f8cb176e2b
Revises: ab2eacaace39
Create Date: 2021-03-26 15:19:35.177318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f8cb176e2b'
down_revision = 'ab2eacaace39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_category_id'), 'product_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_category_product_id'), 'product_category', ['product_id'], unique=False)
    op.drop_table('product_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='product_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_categories_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name='product_categories_pkey')
    )
    op.drop_index(op.f('ix_product_category_product_id'), table_name='product_category')
    op.drop_index(op.f('ix_product_category_category_id'), table_name='product_category')
    op.drop_table('product_category')
    # ### end Alembic commands ###
