"""make restaurant name non-unique

Revision ID: 2aa03cf3b06c
Revises: 5fa1708fc0e6
Create Date: 2021-03-26 14:47:23.106980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa03cf3b06c'
down_revision = '5fa1708fc0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurant_name', table_name='restaurant')
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.create_index('ix_restaurant_name', 'restaurant', ['name'], unique=True)
    # ### end Alembic commands ###
