"""add relationship between restaurants and products

Revision ID: 358ccc7d1b46
Revises: f03e66c6c95a
Create Date: 2021-03-24 14:37:16.360785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358ccc7d1b46'
down_revision = 'f03e66c6c95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_products',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_products')
    # ### end Alembic commands ###
