"""change column type of courier id

Revision ID: 35e79394cf1c
Revises: e8aa103d4311
Create Date: 2021-03-26 13:00:38.845666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e79394cf1c'
down_revision = 'e8aa103d4311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courier', 'fb_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('courier', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('courier', 'vk_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courier', 'vk_id',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('courier', 'tg_id',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('courier', 'fb_id',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
