"""add reference field to cart model

Revision ID: 6d99551dc1cd
Revises: ac36a514f889
Create Date: 2021-03-29 11:04:57.004904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d99551dc1cd'
down_revision = 'ac36a514f889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('reference', sa.String(length=50), nullable=False))
    op.drop_index('ix_cart_customer_id', table_name='cart')
    op.create_index(op.f('ix_cart_reference'), 'cart', ['reference'], unique=True)
    op.drop_constraint('cart_customer_id_fkey', 'cart', type_='foreignkey')
    op.drop_column('cart', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('cart_customer_id_fkey', 'cart', 'customer', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_cart_reference'), table_name='cart')
    op.create_index('ix_cart_customer_id', 'cart', ['customer_id'], unique=True)
    op.drop_column('cart', 'reference')
    # ### end Alembic commands ###
