"""add sqlalchemy_utils column types to restaurant

Revision ID: 7213ece244f7
Revises: 85eff35c69b5
Create Date: 2021-04-03 15:08:15.914890

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7213ece244f7'
down_revision = '85eff35c69b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courier', 'contact_phone',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
               existing_nullable=False)
    op.alter_column('restaurant', 'contact_phone',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'contact_phone',
               existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('courier', 'contact_phone',
               existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
