"""add cart model

Revision ID: 80af27ad948c
Revises: 999988857856
Create Date: 2021-03-28 15:17:58.471757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80af27ad948c'
down_revision = '999988857856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_customer_id'), 'cart', ['customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_customer_id'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
