"""add sqlalchemy_utils column types

Revision ID: 85eff35c69b5
Revises: 4031575c263a
Create Date: 2021-04-03 14:33:22.705588

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85eff35c69b5'
down_revision = '4031575c263a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlalchemy_utils.types.email.EmailType(length=255),
               nullable=True)
    op.drop_index('ix_customer_email', table_name='customer')
    op.alter_column('customer_shipping_address', 'phone_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_shipping_address', 'phone_number',
               existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    op.create_index('ix_customer_email', 'customer', ['email'], unique=True)
    op.alter_column('customer', 'email',
               existing_type=sqlalchemy_utils.types.email.EmailType(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
