"""add restaurant_product table

Revision ID: 964048ead47f
Revises: 2175eaddb802
Create Date: 2021-03-26 16:03:53.919488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964048ead47f'
down_revision = '2175eaddb802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_product_product_id'), 'restaurant_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_restaurant_product_restaurant_id'), 'restaurant_product', ['restaurant_id'], unique=False)
    op.drop_table('restaurant_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_products',
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='restaurant_products_product_id_fkey'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name='restaurant_products_restaurant_id_fkey'),
    sa.PrimaryKeyConstraint('restaurant_id', 'product_id', name='restaurant_products_pkey')
    )
    op.drop_index(op.f('ix_restaurant_product_restaurant_id'), table_name='restaurant_product')
    op.drop_index(op.f('ix_restaurant_product_product_id'), table_name='restaurant_product')
    op.drop_table('restaurant_product')
    # ### end Alembic commands ###
