"""add order_product table

Revision ID: 999988857856
Revises: 964048ead47f
Create Date: 2021-03-26 16:13:08.304070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999988857856'
down_revision = '964048ead47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_product_order_id'), 'order_product', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_product_product_id'), 'order_product', ['product_id'], unique=False)
    op.drop_table('order_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_products',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_products_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_products_product_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name='order_products_pkey')
    )
    op.drop_index(op.f('ix_order_product_product_id'), table_name='order_product')
    op.drop_index(op.f('ix_order_product_order_id'), table_name='order_product')
    op.drop_table('order_product')
    # ### end Alembic commands ###
