"""add restaurant model

Revision ID: b1dbb9a7328e
Revises: fbe91100e8b3
Create Date: 2021-03-24 14:06:14.046523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1dbb9a7328e'
down_revision = 'fbe91100e8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('address', sa.String(length=140), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_phone', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_address'), 'restaurant', ['address'], unique=True)
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_address'), table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
