"""add customer shipping address model

Revision ID: fbe91100e8b3
Revises: a75a12c4cd9a
Create Date: 2021-03-24 10:55:28.112686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe91100e8b3'
down_revision = 'a75a12c4cd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_shipping_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('street', sa.String(length=20), nullable=False),
    sa.Column('house_number', sa.Integer(), nullable=False),
    sa.Column('apartment_number', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_shipping_address_customer_id'), 'customer_shipping_address', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_shipping_address_customer_id'), table_name='customer_shipping_address')
    op.drop_table('customer_shipping_address')
    # ### end Alembic commands ###
